# версия Docker Compose
version: '3.8'

# имена и описания контейнеров, которые должны быть развёрнуты
services:
  gateway:
    build:
      dockerfile: Dockerfile
      context: ./shareit-gateway
    image: shareit_gateway_image
    container_name: shareit_gateway_container
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090
    networks:
      - shareit-net

  server:
    build:
      dockerfile: Dockerfile
      context: ./shareit-server
    image: shareit_server_image
    container_name: shareit_server_container
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      #- DB_NAME=shareit
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      #- DB_HOST=db
      #- DB_PORT=5432
    networks:
      - shareit-net

  # описание контейнера db
  db:
    # образ, из которого должен быть запущен контейнер
    image: postgres:13.7-alpine
    container_name: shareit_db_container
    ports:
      - "6541:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      #- SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - POSTGRES_DB=shareit
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
    networks:
      - shareit-net
networks:
  shareit-net:
    driver: bridge